Webhooks = {
    all = {
        webhook = "DISCORD_WEBHOOK",
        color = "#A1A1A1",
        embed = true
    },
    system = {
        webhook = GetConvar('discord_logs:system', ''),
    },
    imageStore = {
        webhook = GetConvar('discord_logs:imageStore', ''),
    },
    chat = {
        webhook = GetConvar('discord_logs:chat', ''),
        icon = "💬",
        color = "#A1A1A1",
        logHistory = true,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = true,
            Postal = true,
            DiscordID = false,
            License = true,
            License2 = true,
            IP = true,
            PlayTime = true,
            playerPing = true,
            esxName = false,
            esxJob = true,
            esxMoney = true
        },
    },
    joins = {
        webhook = GetConvar('discord_logs:joins', ''),
        icon = "📥",
        color = "#3AF241",
        embed = true,
        Hide = {
            PlayerID = true,
            SteamID = false,
            SteamURL = false,
            Postal = true,
            DiscordID = false,
            License = false,
            License2 = true,
            IP = false,
            PlayTime = false,
            playerPing = true,
            esxName = true,
            esxJob = true,
            esxMoney = true
        },
    },
    leaving = {
        webhook = GetConvar('discord_logs:leaving', ''),
        icon = "📤",
        color = "#F23A3A",
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = true,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
    deaths = {
        webhook = GetConvar('discord_logs:deaths', ''),
        icon = "💀",
        color = "#000000",
        logHistory = true,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = true,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
    shooting = {
        webhook = "DISCORD_WEBHOOK",
        icon = "🔫",
        color = "#2E66F2",
        logHistory = false,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = false,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
    resources = {
        webhook = "DISCORD_WEBHOOK",
        icon = "🔧",
        color = "#EBEE3F",
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = false,
            IP = false,
            PlayTime = false,
            playerPing = false
        },
    },
    nameChange = {
        webhook = "DISCORD_WEBHOOK",
        icon = "⚠",
        color = "#03FC98",
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = false,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
    explosion = {
        webhook = GetConvar('discord_logs:explosion', ''),
        icon = "🧨",
        color = "#03FC98",
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = true,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
    screenshot = {
        webhook = GetConvar('discord_logs:screenshot', ''),
        icon = "📸",
        color = "#A1A1A1",
        logHistory = false,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = true,
            License2 = false,
            IP = false,
            PlayTime = false,
            playerPing = false
        },
    },
    AntiCheat = {
        webhook = "DISCORD_WEBHOOK",
        icon = "⚠",
        color = "#A1A1A1",
        logHistory = false,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = false,
            DiscordID = false,
            License = false,
            License2 = true,
            IP = false,
            PlayTime = false,
            playerPing = false
        },
    },
    moneywash = {
        webhook = GetConvar('discord_logs:moneywash', ''),
        icon = "🏠",
        color = "#ffea05",
        logHistory = false,
        embed = true,
        Hide = {
            PlayerID = false,
            SteamID = false,
            SteamURL = false,
            Postal = true,
            DiscordID = false,
            License = true,
            License2 = false,
            IP = false,
            PlayTime = false,
            playerPing = false,
            esxName = false,
            esxJob = false,
            esxMoney = false
        },
    },
}
