Config.DurabilityBlockedWeapons = {
    ["weapon_stungun"] = true,
    ["weapon_nightstick"] = true,
    ["weapon_flashlight"] = true,
    ["weapon_unarmed"] = true,
    ["weapon_petrolcan"] = true,
	["weapon_fireextinguisher"] = true
}

Config.ItemInformations = {
	["micro_forceps"] = {       type = "uses",          max = 5   },
	["screwdriverset"] = { 		type = "uses",   		max = 5   },
	["bigscissors"] = {    		type = "uses",    		max = 5   },
	["scale"] = {        		type = "uses",    		max = 5   },
	["clubbottle"] = {     		type = "uses",    		max = 10  },
	["harness"] = {        		type = "uses",    		max = 20  },
	["cigarettepack"] = {  		type = "cigarettes",	max = 20  },
	["slimcigarettepack"] = {  	type = "cigarettes",	max = 20  },
	["cubancigarettepack"] = {	type = "cigarettes",	max = 20  },
	["lighter"] = {				type = "uses",			max = 50  },
	["zippo"] = {				type = "uses",			max = 100 },
	["polaroid"] = {       		type = "quality", 		max = 100 },
	["printed_photo"] = {  		type = "quality", 		max = 100 },
	["expiring"] = {       		type = "quality", 		max = 100 },
	["fakeplate"] = {      		type = "health",  		max = 100 },
	["nitrous"] = {  			type = "value",			max = 100 },
	["forestfruitsliquid"] = { 	type = "shots",			max = 100 },
	["energydrinkliquid"] = { 	type = "shots",			max = 100 },
	["cheesecakeliquid"] = { 	type = "shots",			max = 100 },
	["watermelonliquid"] = { 	type = "shots",			max = 100 },
	["strawberryliquid"] = { 	type = "shots",			max = 100 },
	["bubblegumliquid"] = { 	type = "shots",			max = 100 },
	["blueberryliquid"] = { 	type = "shots",			max = 100 },
	["caramelaliquid"] = { 		type = "shots",			max = 100 },
	["cinnamonliquid"] = { 		type = "shots",			max = 100 },
	["vanillaliquid"] = { 		type = "shots",			max = 100 },
	["biscuitliquid"] = { 		type = "shots",			max = 100 },
	["coffeeliquid"] = { 		type = "shots",			max = 100 },
	["bananaliquid"] = { 		type = "shots",			max = 100 },
	["lemonliquid"] = { 		type = "shots",			max = 100 },
	["honeyliquid"] = { 		type = "shots",			max = 100 },
	["mintliquid"] = { 			type = "shots",			max = 100 },
}

Config.DurabilityMultiplier = {
	-- Melee
	['weapon_dagger'] 				 = 0.09,
	['weapon_bat'] 				 	 = 0.09,
	['weapon_bottle'] 				 = 0.09,
	['weapon_crowbar'] 				 = 0.09,
	['weapon_golfclub'] 			 = 0.09,
	['weapon_hammer'] 				 = 0.09,
	['weapon_hatchet'] 				 = 0.09,
	['weapon_knuckle'] 				 = 0.09,
	['weapon_knife'] 				 = 0.09,
	['weapon_machete'] 				 = 0.09,
	['weapon_switchblade'] 			 = 0.09,
	['weapon_wrench'] 				 = 0.09,
	['weapon_battleaxe'] 			 = 0.09,
	['weapon_poolcue'] 				 = 0.09,
	['weapon_briefcase'] 			 = 0.09,
	['weapon_briefcase_02'] 		 = 0.09,
	['weapon_garbagebag'] 			 = 0.09,
	['weapon_handcuffs'] 			 = 0.09,
	['weapon_bread'] 				 = 0.09,
	['weapon_stone_hatchet'] 		 = 0.09,
	-- Handguns
	['weapon_pistol'] 				 = 0.09,
	['weapon_pistol_mk2'] 			 = 0.09,
	['weapon_combatpistol'] 		 = 0.09,
	['weapon_appistol'] 			 = 0.09,
	['weapon_pistol50'] 			 = 0.09,
	['weapon_snspistol'] 			 = 0.09,
	['weapon_heavypistol'] 			 = 0.09,
	['weapon_vintagepistol'] 		 = 0.09,
	['weapon_flaregun'] 			 = 0.09,
	['weapon_marksmanpistol'] 		 = 0.09,
	['weapon_revolver'] 			 = 0.09,
	['weapon_revolver_mk2'] 		 = 0.09,
	['weapon_doubleaction'] 		 = 0.09,
	['weapon_snspistol_mk2'] 		 = 0.09,
	['weapon_raypistol'] 			 = 0.09,
	['weapon_ceramicpistol'] 		 = 0.09,
	['weapon_navyrevolver'] 		 = 0.09,
	['weapon_gadgetpistol'] 		 = 0.09,
	-- Submachine Guns
	['weapon_microsmg'] 			 = 0.09,
	['weapon_smg'] 				     = 0.09,
	['weapon_smg_mk2'] 				 = 0.09,
	['weapon_assaultsmg'] 			 = 0.09,
	['weapon_combatpdw'] 			 = 0.09,
	['weapon_machinepistol'] 		 = 0.09,
	['weapon_minismg'] 				 = 0.09,
	['weapon_raycarbine'] 			 = 0.09,
	-- Shotguns
	['weapon_pumpshotgun'] 			= 0.09,
	['weapon_sawnoffshotgun'] 		= 0.09,
	['weapon_assaultshotgun'] 		= 0.09,
	['weapon_bullpupshotgun'] 		= 0.09,
	['weapon_musket'] 				= 0.09,
	['weapon_heavyshotgun'] 		= 0.09,
	['weapon_dbshotgun'] 			= 0.09,
	['weapon_autoshotgun'] 			= 0.09,
	['weapon_pumpshotgun_mk2'] 		= 0.09,
	['weapon_combatshotgun'] 		= 0.09,
	-- Assault Rifles
	['weapon_assaultrifle'] 		= 0.09,
	['weapon_assaultrifle_mk2'] 	= 0.09,
	['weapon_carbinerifle'] 		= 0.09,
	['weapon_carbinerifle_mk2'] 	= 0.09,
	['weapon_advancedrifle'] 		= 0.09,
	['weapon_specialcarbine'] 		= 0.09,
	['weapon_bullpuprifle'] 		= 0.09,
	['weapon_compactrifle'] 		= 0.09,
	['weapon_specialcarbine_mk2'] 	= 0.09,
	['weapon_bullpuprifle_mk2'] 	= 0.09,
	['weapon_militaryrifle'] 		= 0.09,
    ['weapon_heavyrifle']           = 0.09,
	-- Light Machine Guns
	['weapon_mg'] 				    = 0.09,
	['weapon_combatmg'] 			= 0.09,
	['weapon_gusenberg'] 			= 0.09,
	['weapon_combatmg_mk2'] 		= 0.09,
	-- Sniper Rifles
	['weapon_sniperrifle'] 			= 0.09,
	['weapon_heavysniper'] 			= 0.09,
	['weapon_marksmanrifle'] 		= 0.09,
	['weapon_remotesniper'] 		= 0.09,
	['weapon_heavysniper_mk2'] 		= 0.09,
	['weapon_marksmanrifle_mk2'] 	= 0.09,
	-- Heavy Weapons
	['weapon_rpg'] 				    = 0.09,
	['weapon_grenadelauncher'] 		= 0.09,
	['weapon_grenadelauncher_smoke']= 0.09,
    ['weapon_emplauncher']          = 0.09,
	['weapon_minigun'] 				= 0.09,
	['weapon_firework'] 			= 0.09,
	['weapon_railgun'] 				= 0.09,
	['weapon_hominglauncher'] 		= 0.09,
	['weapon_compactlauncher'] 		= 0.09,
	['weapon_rayminigun'] 			= 0.09,
    ['weapon_glock17']              = 0.09,
	-- Throwables
	['weapon_grenade'] 				= 0.09,
	['weapon_bzgas'] 				= 0.09,
	['weapon_molotov'] 				= 0.09,
	['weapon_stickybomb'] 			= 0.09,
	['weapon_proxmine'] 			= 0.09,
	['weapon_snowball'] 			= 0.09,
	['weapon_pipebomb'] 			= 0.09,
	['weapon_ball'] 				= 0.09,
	['weapon_smokegrenade'] 		= 0.09,
	['weapon_flare'] 				= 0.09,
	-- Miscellaneous
	['weapon_hazardcan'] 			= 0.09,
    ['weapon_fertilizercan'] 		= 0.09,
	['weapon_megaphone']            = 0.09,
}