-- Shop Products by shop type
Config.Products = {
    ["cityhall"] = {
        [1] = {
            name = "id_card",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "driving_license",
            price = 150,
            amount = 1000,
            info = {},
            type = "item",
            license = "dmv",
            slot = 2,
        },
    },
    ["normal"] = {
        [1] = {
            name = "toast",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cigarettepack",
            price = 50,
            amount = 500,
            info = { cigarettes = 20 },
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "slimcigarettepack",
            price = 45,
            amount = 500,
            info = { cigarettes = 20 },
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "cubancigarettepack",
            price = 100,
            amount = 500,
            info = { cigarettes = 20 },
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "lighter",
            price = 5,
            amount = 500,
            info = { uses = 50 },
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "zippo",
            price = 60,
            amount = 500,
            info = { uses = 100 },
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "walkingstick",
            price = 200,
            amount = 100,
            info = {},
            type = "item",
            slot = 8,
        },
    },
    ["farmer"] = {
        [1] = {
            name = "potato_seed",
            price = 10,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "tomato_seed",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "lettuce_seed",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "cucumber_seed",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
    }, 
    ["digitalden"] = {
        [1] = {
            name = "phone",
            price = 10,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "laptop",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "radio",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 3,
        },
    }, 
    ["fisherman"] = {
        [1] = {
            name = "fishingrod",
            price = 10,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "fishingbait",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
    }, 
    ["hunter"] = {
        [1] = {
            name = "weapon_sniperrifle",
            price = 10,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_dagger",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "rifle_ammo",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["blackmarket"] = {
        [1] = {
            name = "hack_usb",
            price = 10,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "drill",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "c4_bomb",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "thermite_bomb",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "laser_drill",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [6] = {
            name = "hack_laptop",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [7] = {
            name = "wifi_scanner",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [8] = {
            name = "e_laptop",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [9] = {
            name = "vpn",
            price = 5,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
    }, 
    ["youtool"] = { 
        [1] = {
            name = "yogamat_red",
            price = 1500,
            amount = 50,
            info = {},
            type = "item",
            slot = 1
        },
        [2] = {
            name = "yogamat_blue",
            price = 1500,
            amount = 50,
            info = {},
            type = "item",
            slot = 2
        },
        [3] = {
            name = "yogamat_black",
            price = 1500,
            amount = 50,
            info = {},
            type = "item",
            slot = 3
        },
        [4] = {
            name = "chair1",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 4
        },
        [5] = {
            name = "chair2",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 5
        },
        [6] = {
            name = "binoculars",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "polaroid",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "polaroid_paper",
            price = 20,
            amount = 100,
            info = {},
            type = "item",
            slot = 8
        },
        [9] = {
            name = "empty_bottle",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "weapon_hatchet",
            price = 150,
            amount = 50,
            info = {},
            type = "weapon",
            slot = 10,
        },
        [11] = {
            name = "micro_forceps",
            price = 320,
            amount = 50,
            info = { uses = 5 },
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "bigscissors",
            price = 320,
            amount = 50,
            info = { uses = 5 },
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "toolkit",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "lowgradefert",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "wateringcan",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "weedbag",
            price = 10,
            amount = 500,
            info = {},
            type = "item",
            slot = 16
        },
        [17] = {
            name = "scale",
            price = 1500,
            amount = 50,
            info = { uses = 5 },
            type = "item",
            slot = 17
        },
        [18] = {
            name = "plasticbag",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 18
        },
        [19] = {
            name = "pickaxe",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 18
        },
    }
}

-- Shop Locations
Config.Locations = {
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(25.05, -1346.76, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3039.54, 584.94, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3242.80, 1000.58, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1728.68, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1960.48, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(548.54, 2670.77, 42.20, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2677.47, 3280.35, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2556.66, 381.37, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(373.268, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(813.09, -781.92, 26.17, 264.81),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket11"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(161.20, 6641.57, 31.70, 224.31),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["247supermarket12"] = {
        ["label"] = "BoilingBroke Penitentiary Shop",
        ["coords"] = vector4(1780.05, 2560.77, 45.67, 173.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-47.17, -1758.48, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.11, -914.35, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1819.68, 793.66, 138.09, 130.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.83, -323.41, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.44, 4923.38, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 0
    },
    ["farmer"] = {
        ["label"] = "Farmer's Paradise",
        ["coords"] = vector4(2338.82, 4862.98, 41.81, 223.08),
        ["ped"] = 'cs_lestercrest',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-seedling",
        ["targetLabel"] = "Farmer's Paradise",
        ["products"] = Config.Products["farmer"],
        ["showblip"] = false,
        ["blipsprite"] = 59,
        ["blipcolor"] = 3
    },
    ["youtool"] = {
        label = "You Tool",
        coords = vector4(2737.37, 3462.10, 55.70, 334.61),
        ped = 'cs_josef',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-screwdriver-wrench",
        targetLabel = "Youtool",
        products = Config.Products["youtool"],
        ["showblip"] = false,
        ["blipsprite"] = 566,
        ["blipcolor"] = 8
    },
    ["bayshw"] = {
        label = "Bay Hardware",
        coords = vector4(-11.07, 6499.33, 31.51, 37.28),
        ped = "cs_josef",
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-screwdriver-wrench",
        targetLabel = "Bay Hardware",
        products = Config.Products["youtool"],
        ["showblip"] = true,
        ["blipsprite"] = 566,
        ["blipcolor"] = 8
    },
    ["megamall"] = {
        label = "Mega Mall",
        coords = vector4(55.27, -1739.50, 29.59, 51.55),
        ped = "cs_josef",
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-screwdriver-wrench",
        targetLabel = "Mega Mall",
        products = Config.Products["youtool"],
        ["showblip"] = true,
        ["blipsprite"] = 566,
        ["blipcolor"] = 8
    },
    ["cityhall"] = {
        label = "City Hall",
        coords = vector4(-542.49, -197.19, 38.27, 76.65),
        ped = 'a_m_m_business_01',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-suitcase",
        targetLabel = "City Hall",
        products = Config.Products["cityhall"],
        ["showblip"] = false,
        ["blipsprite"] = 59,
        ["blipcolor"] = 3
    },
    ["digitalden"] = {
        label = "Digital Den",
        coords = vector4(1135.3, -468.28, 66.49, 156.98),
        ped = 'a_m_m_indian_01',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-kit-phone",
        targetLabel = "Digital",
        products = Config.Products["digitalden"],
        ["showblip"] = false,
        ["blipsprite"] = 153,
        ["blipcolor"] = 2
    },
    ["fisherman"] = {
        label = "Fisher Man",
        coords = vector4(1320.5861, 4314.3252, 38.1408, 123.09),
        ped = 'a_m_m_indian_01',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-kit-phone",
        targetLabel = "Fisher Man",
        products = Config.Products["fisherman"],
        ["showblip"] = true,
        ["blipsprite"] = 68,
        ["blipcolor"] = 2
    },
    ["blackmarket"] = {
        label = "Black Market",
        coords = vector4(2670.27, 1625.91, 24.53, 272.61),
        ped = 'u_m_m_edtoh',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-kit-phone",
        targetLabel = "Black Market",
        products = Config.Products["blackmarket"],
        ["showblip"] = true,
        ["blipsprite"] = 153,
        ["blipcolor"] = 2
    },
    ["hunter"] = {
        label = "Hunter Market",
        coords = vector4(12.843, 3686.672, 39.649, 233.357),
        ped = 's_m_m_ammucountry',
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",
        radius = 1.5,
        targetIcon = "fas fa-kit-phone",
        targetLabel = "Hunter Market",
        products = Config.Products["hunter"],
        ["showblip"] = true,
        ["blipsprite"] = 59,
        ["blipcolor"] = 2
    },
}