Config.Smoking = {
    Armor = 50,
    AddArmor = true,
    CigaretteExhale = 0.15,
    CigarExhale = 0.15,
    JointExhale = 0.15,
    VapeExhale = 0.4,
    BongExhale = 0.4,
    JointSmoke = 0.03,
    CigarSmoke = 0.05,
    CigaretteSmoke = 0.03,
    SizeRemove = {min = 1, max = 3},
    ExhaleTime = {min = 1000, max = 1500},
    DisableCombatButtons = true,
    SmokeButton = 144,
    ThrowButton = 73,
    MouthButton = 10,
    HandButton = 11,
    GiveButton = 121,
    ConfirmGiveButton = 38,
    CancelGiveButton = 73,
    ItemVapeLiquid = 'liquid',
    MaxLiquid = 6,
    AddLiquidInVape = 5,
    VapeSizeRemove = 0.5,
    MaxWeed = 2,
    AddWeedInBong = 1,
    BongSizeRemove = 1,
    Rollingpaper = 'ocbpaper',
    BongReloadItems = {
        {Items = "og_kush_weed", ItemsLabel = "Og Kush Weed"},
        {Items = "blue_dream_weed", ItemsLabel = "Blue Dream Weed"},
        {Items = "banana_kush_weed", ItemsLabel = "Banana Kush Weed"},
        {Items = "purple_haze_weed", ItemsLabel = "Purple Haze Weed"},
    },
    ItemWeed = {
        'banana_kush_bag',
        'blue_dream_bag',
        'og_kush_bag',
        'purple_haze_bag'
    },
    Liquids = {
        "forestfruitsliquid",
        "energydrinkliquid",
        "cheesecakeliquid",
        "watermelonliquid",
        "strawberryliquid",
        "bubblegumliquid",
        "blueberryliquid",
        "caramelaliquid",
        "cinnamonliquid",
        "vanillaliquid",
        "biscuitliquid",
        "coffeeliquid",
        "bananaliquid",
        "lemonliquid",
        "honeyliquid",
        "mintliquid",
    }
}