Config.Weapons = {
    backslots = {
        rifle = {
            {
                back_bone = 24816, 
                x = 0.075,
                y = -0.15,
                z = 0.08,
                x_rotation = 180.0,
                y_rotation = 0.0,
                z_rotation = 0.0,
                isOccupied = false,
                category = "r_left"
            },
            {
                back_bone = 24816, 
                x = 0.175, 
                y = -0.15, 
                z = -0.12, 
                x_rotation = 0.0, 
                y_rotation = 0.0, 
                z_rotation = 0.0,
                isOccupied = false,
                category = "r_right"
            },
        },
        melee = {
            {
                back_bone = 24816, 
                x = -0.075, 
                y = -0.15, 
                z = -0.06, 
                x_rotation = 0.0, 
                y_rotation = 90.0, 
                z_rotation = 0.0,
                isOccupied = false,
                category = "r_mid"
            },
        },
        pistol = {
            { --RIGHT
                back_bone = 51826, 
                x = 0.075,
                y = 0.03,
                z = 0.10,
                x_rotation = -90.0,
                y_rotation = 90.0,
                z_rotation = 90.0,
                isOccupied = false,
                category = "p_right"
            },
            { --LEFT
                back_bone = 58271, 
                x = 0.075,
                y = 0.03,
                z = -0.10,
                x_rotation = -90.0,
                y_rotation = 90.0,
                z_rotation = 90.0,
                isOccupied = false,
                category = "p_left"
            },
        }
    },
    compatable_weapon_hashes = {
        ["w_me_bat"] = { 
            hash = GetHashKey("WEAPON_BAT"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_hatchet"] = { 
            hash = GetHashKey("weapon_hatchet"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_crowbar"] = { 
            hash = GetHashKey("weapon_crowbar"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_hammer"] = { 
            hash = GetHashKey("weapon_hammer"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_gclub"] = { 
            hash = GetHashKey("weapon_golfclub"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_machette_lr"] = { 
            hash = GetHashKey("weapon_machete"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_knuckle"] = { 
            hash = GetHashKey("weapon_knuckle"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_knife_01"] = { 
            hash = GetHashKey("weapon_knife"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_me_dagger"] = { 
            hash = GetHashKey("weapon_dagger"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_pe"] = {
            hash = GetHashKey("weapon_stickybomb"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_grenadesmoke"] = {
            hash = GetHashKey("weapon_bzgas"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_grenadesmoke"] = {
            hash = GetHashKey("weapon_smokegrenade"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_apmine"] = {
            hash = GetHashKey("weapon_proxmine"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_molotov"] = {
            hash = GetHashKey("weapon_molotov"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_ex_grenadefrag"] = {
            hash = GetHashKey("weapon_grenade"),
            back_bone = 24816, 
            x = -0.075, 
            y = -0.15, 
            z = -0.06, 
            x_rotation = 0.0, 
            y_rotation = 90.0, 
            z_rotation = 0.0 
        },
        ["w_pi_pistol"] = {
            hash = GetHashKey('WEAPON_PISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_sns_pistol"] = {
            hash = GetHashKey('WEAPON_SNSPISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_appistol"] = {
            hash = GetHashKey('WEAPON_APPISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_vintage_pistol"] = {
            hash = GetHashKey('WEAPON_VINTAGEPISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_combatpistol"] = {
            hash = GetHashKey('WEAPON_COMBATPISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_heavypistol"] = {
            hash = GetHashKey('WEAPON_HEAVYPISTOL'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_pi_pistol50"] = {
            hash = GetHashKey('WEAPON_PISTOL50'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_sb_compactsmg"] = {
            hash = GetHashKey('weapon_machinepistol'),
            back_bone = 58271, 
            x = 0.075,
            y = 0.03,
            z = -0.10,
            x_rotation = -90.0,
            y_rotation = 90.0,
            z_rotation = 90.0,
            isOccupied = false,
        },
        ["w_sb_microsmg"] = { 
            hash = 324215364, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sb_assaultsmg"] = { 
            hash = -270015777, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sb_smg"] = { 
            hash = 736523883, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0,
            z_rotation = 0.0 
        },
        ["w_sb_pdw"] = {
            hash = 171789620, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sb_gusenberg"] = { 
            hash = 1627465347, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sg_sawnoff"] = {
            hash = 2017895192, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sg_pumpshotgun"] = { 
            hash = 487013001, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sg_heavyshotgun"] = { 
            hash = GetHashKey("WEAPON_HEAVYSHOTGUN"), 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_sr_huntingrifle"] = { 
            hash = GetHashKey('WEAPON_HUNTINGRIFLE'), 
            back_bone = 24816, 
            x = 0.075,
            y = -0.15,
            z = 0.08,
            x_rotation = 180.0,
            y_rotation = 5.0,
            z_rotation = 0.0
        },
        ["w_mg_mg"] = { 
            hash = -1660422300, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_mg_combatmg"] = { 
            hash = 2144741730, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_ar_assaultrifle"] = { 
            hash = -1074790547, 
            back_bone = 24816, 
            x = 0.175, 
            y = -0.15, 
            z = -0.00, 
            x_rotation = 180.0, 
            y_rotation = 0.0, 
            z_rotation = 0.0 
        },
        ["w_ar_carbinerifle"] = {
            hash = -2084633992,
            back_bone = 24816, 
            x = 0.175, 
            y = -0.15, 
            z = -0.12, 
            x_rotation = 0.0, 
            y_rotation = 5.0, 
            z_rotation = 0.0 
        },
        ["w_ar_bullpuprifle"] = { 
            hash = 2132975508, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_ar_advancedrifle"] = { 
            hash = -1357824103, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 165.0, 
            z_rotation = 0.0 
        },
        ["w_ar_specialcarbine"] = { 
            hash = -1063057011, 
            back_bone = 24816, 
            x = 0.075, 
            y = -0.15, 
            z = -0.02, 
            x_rotation = 0.0, 
            y_rotation = 35.0, 
            z_rotation = 0.0 
        },
    }
}