REPLACE INTO items (`name`,`label`,`weight`) VALUES
    ('boostingtab', 'Boosting Tablet', 1),
    ('lockpick', 'Lockpick', 1),
    ('hackingtab', 'Hacking Tablet', 1),
    ('xenonsbleu', 'Blue Xenons', 1),
    ('xenonsbleuelect', 'Electric Blue Xenons', 1),
    ('xenonsmenthe', 'Mint Xenons', 1),
    ('xenonsvert', 'Green Xenons', 1),
    ('xenonsjaune', 'Yellow Xenons', 1),
    ('xenonsgold', 'Gold Xenons', 1),
    ('xenonsorange', 'Orange Xenons', 1),
    ('xenonsrouge', 'Red Xenons', 1),
    ('xenonsrose', 'Pink Xenons', 1),
    ('xenonsrose2', 'Hot Pink Xenons', 1),
    ('xenonsmauve', 'Purple Xenone', 1),
    ('xenonsblacklight', 'Blacklight Xenons', 1),
    ('xenonsdefault', 'White Xenons', 1),
    ('turbo', 'Turbo Kit', 1),
    ('engine1', 'Engine Lvl. 1', 1),
    ('engine2', 'Engine Lvl. 2', 1),
    ('engine3', 'Engine Lvl. 3', 1),
    ('engine4', 'Engine Lvl. 4', 1),
    ('brakes1', 'Brakes Lvl. 1', 1),
    ('brakes2', 'Brakes Lvl. 2', 1),
    ('brakes3', 'Brakes Lvl. 3', 1),
    ('trans1', 'Transmission Lvl. 1', 1),
    ('trans2', 'Transmission Lvl. 2', 1),
    ('trans3', 'Transmission Lvl. 3', 1),
    ('susp1', 'Suspension Lvl. 1', 1),
    ('susp2', 'Suspension Lvl. 2', 1),
    ('susp3', 'Suspension Lvl. 3', 1),
    ('susp4', 'Suspension Lvl. 4', 1),
    ('arm1', 'Armor Lvl. 1', 1),
    ('arm2', 'Armor Lvl. 2', 1),
    ('arm3', 'Armor Lvl. 3', 1),
    ('arm4', 'Armor Lvl. 4', 1),
    ('arm5', 'Armor Lvl. 5', 1),
    ('win1', 'Light Smoke Window Tint', 1),
    ('win2', 'Dark Smoke Window Tint', 1),
    ('win3', 'Limo Window Tint', 1)
;
