-- Item registration
-- some item included in default are from my server remove it if you dont have the item
Config.ItemsOnback = {
	["pickaxe"] = { -- Item Name
        model="prop_tool_pickaxe", -- Model you want to display
        back_bone = 24817, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.05,
        y = -0.09,
        z = 0.08,
        -- Rotaion of the object.
        x_rotation = 5.0,
        y_rotation = -244.72,
        z_rotation = -1.5,
    },
	["baglvl1"] = { -- Item Name
        model="prop_michael_backpack", -- Model you want to display
        back_bone = 24817, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = 0.2,
        y = -0.15,
        z = 0.0,
        -- Rotaion of the object.
        x_rotation = 9.0,
        y_rotation = -100.17,
        z_rotation = 193.87,
    },
	["baglvl2"] = { -- Item Name
        model="vw_prop_vw_backpack_01a", -- Model you want to display
        back_bone = 24817, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.1 ,
        y = -0.1,
        z = 0.0099999999999992,
        -- Rotaion of the object.
        x_rotation = -1.4999999999999 ,
        y_rotation = -94.969999999999,
        z_rotation =  193.87,
    },
	["baglvl3"] = { -- Item Name
        model="sf_prop_sf_backpack_03a", -- Model you want to display
        back_bone = 24817, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = 0.2,
        y = -0.15,
        z = 0.0,
        -- Rotaion of the object.
        x_rotation = 9.0,
        y_rotation = -100.17,
        z_rotation = 193.87,
    },
	["WEAPON_BZGAS"] = { -- Item Name
        model="prop_gas_grenade", -- Model you want to display
        back_bone = 23553, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.04,
        y = 0.12,
        z = -0.16,
        -- Rotaion of the object.
        x_rotation = 85.45,
        y_rotation = 8.6499999999999,
        z_rotation = 87.19,
    },

	["WEAPON_POKEBALL"] = { -- Item Name
        model="w_am_pokeball", -- Model you want to display
        back_bone = 23553, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -1.3877787807814e-17,
        y = 1.3877787807814e-17,
        z = -0.2,
        -- Rotaion of the object.
        x_rotation = 0.0,
        y_rotation = 20.25,
        z_rotation = 0.0,
    },
	-- ["repairkit"] = { -- Item Name
    --     model="prop_tool_box_04", -- Model you want to display
    --     back_bone = 23553, -- PED bone the entity is attached to.
    --     -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
    --     x = -0.15,
    --     y = -0.2,
    --     z = 0.05,
    --     -- Rotaion of the object.
    --     x_rotation = 0.0,
    --     y_rotation = -265.30000000003,
    --     z_rotation = -4.6,
    -- },

    -- ["meth"] = {
    --     model="hei_prop_pill_bag_01", 
    --     back_bone = 24818,
    --     x = -0.1,
    --     y = -0.17,
    --     z = 0.12,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 0.0,
    -- },
    
	["WEAPON_MICROSMG"] = {
        model="w_sb_microsmg", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },
	["WEAPON_GHOST"] = {
        model="w_pi_ghost", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },
	["WEAPON_PISTOL"] = {
        model="w_pi_pistol", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },
	["WEAPON_HEAVYPISTOL"] = {
        model="w_pi_heavypistol", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },
	["WEAPON_MINISMG"] = {
        model="w_sb_minismg", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },
	["WEAPON_MACHINEPISTOL"] = {
        model="w_sb_compactsmg", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },

    ["WEAPON_BULLPUPSHOTGUN"] = {
        model="w_sg_bullpupshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_ADVANCEDRIFLE"] = {
        model="W_AR_ADVANCEDRIFLE", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_PRECISIONRIFLE"] = {
        model="W_SR_PrecisionRifle_REH", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_BULLPUPRIFLE_MK2"] = {
        model="w_ar_bullpupriflemk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_GUSENBERG"] = {
        model="w_sb_gusenberg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_DBSHOTGUN"] = {
        model="w_sg_doublebarrel", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_APPISTOL"] = {
        model="W_PI_APPISTOL", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },

    ["WEAPON_PUMPSHOTGUN_MK2"] = {
        model="w_sg_pumpshotgunmk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_COMPACTRIFLE"] = {
        model="w_ar_assaultrifle_smg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_SMG"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_GUSENBERG"] = {
        model="w_sb_gusenberg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_PUMPSHOTGUN"] = {
        model="w_sg_pumpshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["WEAPON_ASSAULTRIFLE_MK2"] = {
        model="w_ar_assaultriflemk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_SAWNOFFSHOTGUN"] = {
        model="w_sg_sawnoff", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_HEAVYSNIPER_MK2"] = {
        model="w_sr_heavysnipermk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MARKSMANRIFLE_MK2"] = {
        model="w_sr_marksmanriflemk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_HEAVYSNIPER"] = {
        model="w_sr_heavysniper", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_COMBATMG_MK2"] = {
        model="w_mg_combatmgmk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MG"] = {
        model="w_mg_mg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_AUTOSHOTGUN"] = {
        model="w_sg_sweeper", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MUSKET"] = {
        model="w_ar_musket", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_COMBATPDW"] = {
        model="W_SB_PDW", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_COMBATSHOTGUN"] = {
        model="w_sg_pumpshotgunh4", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_TACTICALRIFLE"] = {
        model="W_AR_CARBINERIFLE_REH", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MILITARYRIFLE"] = {
        model="w_ar_bullpuprifleh4", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_SNIPERRIFLE"] = {
        model="w_sr_sniperrifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_SMG_MK2"] = {
        model="w_sb_smgmk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_ASSAULTSHOTGUN"] = {
        model="w_sg_assaultshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MARKSMANRIFLE"] = {
        model="w_sr_marksmanrifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_HEAVYSHOTGUN"] = {
        model="w_sg_heavyshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_MINIGUN"] = {
        model="w_mg_minigun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_CARBINERIFLE_MK2"] = {
        model="w_ar_carbineriflemk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_HEAVYRIFLE"] = {
        model="w_ar_heavyrifleh", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_SPECIALCARBINE_MK2"] = {
        model="w_ar_specialcarbinemk2", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["WEAPON_CERAMICPISTOL"] = {
        model="w_sb_assaultsmg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

	["WEAPON_SNSPISTOL_MK2"] = {
        model="w_pi_sns_pistolmk2", 
        back_bone = 23553,
        x = 0.03,
        y = 0.04,
        z = -0.19,
        x_rotation = 68.38,
        y_rotation = 19.700000000001,
        z_rotation = 173.89,
    },

	["WEAPON_ASSAULTSMG"] = {
        model="w_sb_assaultsmg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["WEAPON_ASSAULTRIFLE"] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_CARBINERIFLE"] = {
        model="w_ar_carbinerifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["WEAPON_SPECIALCARBINE"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_BULLPUPRIFLE"] = {
        model="w_ar_bullpuprifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_RGXVANDAL"] = {
        model="w_ar_rgxvandal", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_FIREKATANA"] = {
        model="w_me_firekatana", 
        back_bone = 23553,
        x = 0.11,
        y = 0.059999999999998,
        z = -0.2,
        x_rotation = -89.5,
        y_rotation = 0.75,
        z_rotation = 107.64,
    },
	["WEAPON_NOTZSAKURA"] = {
        model="w_me_NOTZSAKURA", 
        back_bone = 23553,
        x = 0.11,
        y = 0.059999999999998,
        z = -0.2,
        x_rotation = -89.5,
        y_rotation = 0.75,
        z_rotation = 107.64,
    },
	["WEAPON_TRIDENT"] = {
        model="w_me_TRIDENT", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 180.0,
    },
	["WEAPON_FIRESICKLE"] = {
        model="w_me_firesickle", 
        back_bone = 23553,
        x = -3.1225022567583e-17,
        y = -0.23,
        z = 0.059999999999906,
        x_rotation = -11.17,
        y_rotation = -246.34,
        z_rotation = 1.73,
    },
	["WEAPON_BLACKPINK"] = {
        model="w_me_BLACKPINK", 
        back_bone = 23553,
        x = 0.16,
        y = -0.17,
        z = 0.059999999999906,
        x_rotation = 4.3,
        y_rotation = -246.34,
        z_rotation = 1.73,
    },
	["WEAPON_HAMMERTHOR"] = {
        model="w_me_HAMMERTHOR", 
        back_bone = 24818,
        x = 0.23,
        y = -0.16,
        z = -0.08,
        x_rotation = -9.0999999999999,
        y_rotation = -77.69,
        z_rotation = 264.28,
    },
	["WEAPON_FANHAND"] = {
        model="w_me_FANHAND", 
        back_bone = 24818,
        x = 0.12,
        y = -0.16,
        z = 0.0,
        x_rotation = 13.0,
        y_rotation = -84.5,
        z_rotation = -2.0,
    },
	["WEAPON_MUWEBZEN"] = {
        model="w_me_muwebzen", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 180.0,
    },
	["WEAPON_BAT"] = {
        model="w_me_bat", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 180.0,
    },
	["WEAPON_SWITCHBLADE"] = {
        model="w_me_switchblade", 
        back_bone = 23553,
        x = 0.09,
        y = -0.029999999999959,
        z = -0.16,
        x_rotation = -103.58,
        y_rotation =  11.9,
        z_rotation = 116.31,
    },
	["handcuffs"] = {
        model="p_cs_cuffs_02_s", 
        back_bone = 23553,
        x = -0.02,
        y = 0.1,
        z = 0.17,
        x_rotation = -54.62,
        y_rotation =  18.73,
        z_rotation = 11.89,
    },

	["WEAPON_OPERATOR"] = {
        model="w_sr_operator", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_ELDERVANDAL"] = {
        model="w_ar_eldervandal", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_PRIMEVANDAL"] = {
        model="w_ar_primevandal", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_GPHAN"] = {
        model="w_ar_gphan", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_BPHAN"] = {
        model="w_ar_m16", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_M4"] = {
        model="w_ar_m4", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_DRACOAK"] = {
        model="w_ar_dracoak", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_ASSAAK"] = {
        model="w_ar_assaak", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_M16"] = {
        model="w_ar_goldphan", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
	["WEAPON_REAVERVANDAL"] = {
        model="w_ar_reavervandal", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_rpg"] = {
        model="w_lr_rpg", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    -- ["coke"] = {
    --     model="h4_prop_h4_coke_bottle_01a", 
    --     back_bone = 24818,
    --     x = -0.20,
    --     y = -0.17,
    --     z = 0.0,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 90.0,
    -- },
	-- ["cocaine_cut"] = {
    --     model="prop_coke_block_half_a", 
    --     back_bone = 24818,
    --     x = -0.20,
    --     y = -0.17,
    --     z = 0.0,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 90.0,
    -- },
	-- ["cocaine_uncut"] = {
    --     model="bkr_prop_coke_cutblock_01", 
    --     back_bone = 24818,
    --     x = -0.20,
    --     y = -0.17,
    --     z = 0.0,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 90.0,
    -- },
    ["weed"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
	["weed_untrimmed"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
	-- ["meth_raw"] = {
    --     model="hei_prop_pill_bag_01", 
    --     back_bone = 24818,
    --     x = -0.20,
    --     y = -0.17,
    --     z = 0.0,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 0.0,
    -- },
	-- ["meth_packaged"] = {
    --     model="hei_prop_pill_bag_01", 
    --     back_bone = 24818,
    --     x = -0.20,
    --     y = -0.17,
    --     z = 0.0,
    --     x_rotation = 0.0,
    --     y_rotation = 90.0,
    --     z_rotation = 0.0,
    -- },
}

components_data = { 
    { bone = "WAPCover", name =  "COMPONENT_AT_RAILCOVER_01", model =  "w_at_railcover_01" }, 
    { bone = "WAPGrip", name =  "COMPONENT_AT_AR_AFGRIP", model =  "w_at_ar_afgrip" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_FLSH", model =  "w_at_pi_flsh" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_AR_FLSH", model =  "w_at_ar_flsh" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO", model =  "w_at_scope_macro" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_02", model =  "w_at_scope_macro_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL", model =  "w_at_scope_small" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL_02", model =  "w_at_scope_small_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MEDIUM", model =  "w_at_scope_medium" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE", model =  "w_at_scope_large" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MAX", model =  "w_at_scope_max" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_SUPP", model =  "w_at_pi_supp" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_SUPP_02", model =  "w_at_pi_supp_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_AR_SUPP", model =  "w_at_ar_supp" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_AR_SUPP_02", model =  "w_at_ar_supp_02" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_SR_SUPP", model =  "w_at_sr_supp_2" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_CLIP_01", model =  "w_pi_pistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_CLIP_02", model =  "w_pi_pistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPISTOL_CLIP_01", model =  "w_pi_combatpistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPISTOL_CLIP_02", model =  "w_pi_combatpistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_APPISTOL_CLIP_01", model =  "w_pi_appistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_APPISTOL_CLIP_02", model =  "w_pi_appistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MICROSMG_CLIP_01", model =  "w_sb_microsmg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MICROSMG_CLIP_02", model =  "w_sb_microsmg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_CLIP_01", model =  "w_sb_smg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_CLIP_02", model =  "w_sb_smg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_CLIP_01", model =  "w_ar_assaultrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_CLIP_02", model =  "w_ar_assaultrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_CLIP_01", model =  "w_ar_carbinerifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_CLIP_02", model =  "w_ar_carbinerifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ADVANCEDRIFLE_CLIP_01", model =  "w_ar_advancedrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ADVANCEDRIFLE_CLIP_02", model =  "w_ar_advancedrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MG_CLIP_01", model =  "w_mg_mg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MG_CLIP_02", model =  "w_mg_mg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_CLIP_01", model =  "w_mg_combatmg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_CLIP_02", model =  "w_mg_combatmg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSHOTGUN_CLIP_01", model =  "w_sg_assaultshotgun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSHOTGUN_CLIP_02", model =  "w_sg_assaultshotgun_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNIPERRIFLE_CLIP_01", model =  "w_sr_sniperrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_CLIP_01", model =  "w_sr_heavysniper_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL50_CLIP_01", model =  "W_PI_PISTOL50_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL50_CLIP_02", model =  "W_PI_PISTOL50_Mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSMG_CLIP_01", model =  "W_SB_ASSAULTSMG_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSMG_CLIP_02", model =  "W_SB_ASSAULTSMG_Mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_CLIP_03", model =  "w_ar_assaultrifle_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_CLIP_03", model =  "w_ar_carbinerifle_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPDW_CLIP_03", model =  "w_sb_pdw_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMPACTRIFLE_CLIP_03", model =  "w_ar_assaultrifle_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSHOTGUN_CLIP_03", model =  "w_sg_heavyshotgun_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_MACHINEPISTOL_CLIP_03", model =  "w_sb_compactsmg_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_CLIP_03", model =  "w_sb_smg_boxmag" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_CLIP_03", model =  "w_ar_specialcarbine_boxmag" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO", model =  "w_ar_bullpupriflemk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_02", model =  "w_ar_bullpupriflemk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_03", model =  "w_ar_bullpupriflemk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_04", model =  "w_ar_bullpupriflemk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_05", model =  "w_ar_bullpupriflemk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06", model =  "w_ar_bullpupriflemk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07", model =  "w_ar_bullpupriflemk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08", model =  "w_ar_bullpupriflemk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09", model =  "w_ar_bullpupriflemk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10", model =  "w_ar_bullpupriflemk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01", model =  "w_ar_bullpupriflemk2_camo_ind1" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", model =  "w_ar_bullpupriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", model =  "w_ar_bullpupriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", model =  "W_AR_BullpupRifleMK2_Mag_AP" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", model =  "W_AR_BullpupRifleMK2_Mag_FMJ" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", model =  "W_AR_BullpupRifleMK2_Mag_INC" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", model =  "W_AR_BullpupRifleMK2_Mag_TR" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_BP_BARREL_01", model =  "W_AR_BP_MK2_Barrel1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_BP_BARREL_02", model =  "W_AR_BP_MK2_Barrel2" }, 
    { bone = "WAPClip", name =  "COMPONENT_DOUBLEACTION_CLIP_01", model =  "w_pi_wep1_mag1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO", model =  "w_sr_marksmanriflemk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02", model =  "w_sr_marksmanriflemk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03", model =  "w_sr_marksmanriflemk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04", model =  "w_sr_marksmanriflemk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05", model =  "w_sr_marksmanriflemk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06", model =  "w_sr_marksmanriflemk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07", model =  "w_sr_marksmanriflemk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08", model =  "w_sr_marksmanriflemk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09", model =  "w_sr_marksmanriflemk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10", model =  "w_sr_marksmanriflemk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01", model =  "w_sr_marksmanriflemk2_camo_ind" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01", model =  "w_sr_marksmanriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02", model =  "w_sr_marksmanriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING", model =  "w_sr_marksmanriflemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ", model =  "w_sr_marksmanriflemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY", model =  "w_sr_marksmanriflemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER", model =  "w_sr_marksmanriflemk2_mag_tr" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MRFL_BARREL_01", model =  "w_sr_mr_mk2_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MRFL_BARREL_02", model =  "w_sr_mr_mk2_barrel_2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO", model =  "w_sg_pumpshotgunmk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02", model =  "w_sg_pumpshotgunmk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03", model =  "w_sg_pumpshotgunmk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04", model =  "w_sg_pumpshotgunmk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05", model =  "w_sg_pumpshotgunmk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06", model =  "w_sg_pumpshotgunmk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07", model =  "w_sg_pumpshotgunmk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08", model =  "w_sg_pumpshotgunmk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09", model =  "w_sg_pumpshotgunmk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10", model =  "w_sg_pumpshotgunmk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01", model =  "w_sg_pumpshotgunmk2_camo_ind1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", model =  "w_sg_pumpshotgunmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING", model =  "w_sg_pumpshotgunmk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", model =  "w_sg_pumpshotgunmk2_mag_exp" }, 
    { bone = "WAPClip", name =  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT", model =  "w_sg_pumpshotgunmk2_mag_hp" }, 
    { bone = "WAPClip", name =  "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", model =  "w_sg_pumpshotgunmk2_mag_inc" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO", model =  "w_pi_revolvermk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_02", model =  "w_pi_revolvermk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_03", model =  "w_pi_revolvermk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_04", model =  "w_pi_revolvermk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_05", model =  "w_pi_revolvermk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_06", model =  "w_pi_revolvermk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_07", model =  "w_pi_revolvermk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_08", model =  "w_pi_revolvermk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_09", model =  "w_pi_revolvermk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_10", model =  "w_pi_revolvermk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_REVOLVER_MK2_CAMO_IND_01", model =  "w_pi_revolvermk2_camo_ind" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_MK2_CLIP_01", model =  "w_pi_revolvermk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_MK2_CLIP_FMJ", model =  "w_pi_revolvermk2_mag5" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT", model =  "w_pi_revolvermk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY", model =  "w_pi_revolvermk2_mag3" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_MK2_CLIP_TRACER", model =  "w_pi_revolvermk2_mag4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO", model =  "W_PI_SNS_PistolMk2_Camo1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_02", model =  "W_PI_SNS_PistolMk2_Camo2" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_03", model =  "W_PI_SNS_PistolMk2_Camo3" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_04", model =  "W_PI_SNS_PistolMk2_Camo4" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_05", model =  "W_PI_SNS_PistolMk2_Camo5" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_06", model =  "W_PI_SNS_PistolMk2_Camo6" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_07", model =  "W_PI_SNS_PistolMk2_Camo7" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_08", model =  "W_PI_SNS_PistolMk2_Camo8" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_09", model =  "W_PI_SNS_PistolMk2_Camo9" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_10", model =  "W_PI_SNS_PistolMk2_Camo10" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE", model =  "W_PI_SNS_PistolMk2_SL_Camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01", model =  "w_pi_sns_pistolmk2_camo_ind1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE", model =  "W_PI_SNS_PistolMK2_SL_Camo_Ind1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_01", model =  "w_pi_sns_pistolmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_02", model =  "w_pi_sns_pistolmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ", model =  "W_PI_SNS_PistolMK2_Mag_FMJ" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT", model =  "W_PI_SNS_PistolMK2_Mag_HP" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY", model =  "W_PI_SNS_PistolMK2_Mag_INC" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER", model =  "W_PI_SNS_PistolMK2_Mag_TR" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO", model =  "w_ar_specialcarbinemk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_02", model =  "w_ar_specialcarbinemk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_03", model =  "w_ar_specialcarbinemk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_04", model =  "w_ar_specialcarbinemk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_05", model =  "w_ar_specialcarbinemk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_06", model =  "w_ar_specialcarbinemk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_07", model =  "w_ar_specialcarbinemk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_08", model =  "w_ar_specialcarbinemk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_09", model =  "w_ar_specialcarbinemk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_10", model =  "w_ar_specialcarbinemk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01", model =  "w_ar_specialcarbinemk2_camo_ind" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_01", model =  "w_ar_specialcarbinemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", model =  "w_ar_specialcarbinemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", model =  "w_ar_specialcarbinemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", model =  "w_ar_specialcarbinemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", model =  "w_ar_specialcarbinemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", model =  "w_ar_specialcarbinemk2_mag_tr" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SC_BARREL_01", model =  "w_ar_sc_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SC_BARREL_02", model =  "w_ar_sc_barrel_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_COMP_02", model =  "w_at_pi_comp_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_COMP_03", model =  "w_at_pi_comp_3" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_RAIL_02", model =  "w_at_pi_rail_2" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_FLSH_03", model =  "w_at_pi_snsmk2_flsh_1" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2", model =  "w_at_scope_large" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", model =  "w_ar_assaultriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", model =  "w_ar_assaultriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", model =  "w_ar_assaultriflemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", model =  "w_ar_assaultriflemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", model =  "w_ar_assaultriflemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", model =  "w_ar_assaultriflemk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_01", model =  "w_ar_carbineriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_02", model =  "w_ar_carbineriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", model =  "w_ar_carbineriflemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", model =  "w_ar_carbineriflemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", model =  "w_ar_carbineriflemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", model =  "w_ar_carbineriflemk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_01", model =  "w_mg_combatmgmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_02", model =  "w_mg_combatmgmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", model =  "w_mg_combatmgmk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_FMJ", model =  "w_mg_combatmgmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", model =  "w_mg_combatmgmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_TRACER", model =  "w_mg_combatmgmk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_01", model =  "w_sr_heavysnipermk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", model =  "w_sr_heavysnipermk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", model =  "w_sr_heavysnipermk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", model =  "w_sr_heavysnipermk2_mag_ap2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", model =  "w_sr_heavysnipermk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", model =  "w_sr_heavysnipermk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_01", model =  "w_pi_pistolmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_02", model =  "w_pi_pistolmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_FMJ", model =  "w_pi_pistolmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", model =  "w_pi_pistolmk2_mag_hp" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", model =  "w_pi_pistolmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_TRACER", model =  "w_pi_pistolmk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_01", model =  "w_sb_smgmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_02", model =  "w_sb_smgmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_FMJ", model =  "w_sb_smgmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", model =  "w_sb_smgmk2_mag_hp" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_INCENDIARY", model =  "w_sb_smgmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_TRACER", model =  "w_sb_smgmk2_mag_tr" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_AR_BARREL_01", model =  "w_at_ar_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_AR_BARREL_02", model =  "w_at_ar_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_CR_BARREL_01", model =  "w_at_cr_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_CR_BARREL_02", model =  "w_at_cr_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MG_BARREL_01", model =  "w_at_mg_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MG_BARREL_02", model =  "w_at_mg_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SB_BARREL_01", model =  "w_at_sb_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SB_BARREL_02", model =  "w_at_sb_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SR_BARREL_01", model =  "w_at_sr_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SR_BARREL_02", model =  "w_at_sr_barrel_2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO", model =  "w_at_armk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", model =  "w_at_armk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", model =  "w_at_armk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", model =  "w_at_armk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", model =  "w_at_armk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", model =  "w_at_armk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07", model =  "w_at_armk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", model =  "w_at_armk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", model =  "w_at_armk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", model =  "w_at_armk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01", model =  "w_at_armk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO", model =  "w_ar_carbineriflemk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_02", model =  "w_ar_carbineriflemk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_03", model =  "w_ar_carbineriflemk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_04", model =  "w_ar_carbineriflemk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_05", model =  "w_ar_carbineriflemk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_06", model =  "w_ar_carbineriflemk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_07", model =  "w_ar_carbineriflemk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_08", model =  "w_ar_carbineriflemk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_09", model =  "w_ar_carbineriflemk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_10", model =  "w_ar_carbineriflemk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01", model =  "w_ar_carbineriflemk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO", model =  "w_mg_combatmgmk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_02", model =  "w_mg_combatmgmk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_03", model =  "w_mg_combatmgmk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_04", model =  "w_mg_combatmgmk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_05", model =  "w_mg_combatmgmk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_06", model =  "w_mg_combatmgmk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_07", model =  "w_mg_combatmgmk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_08", model =  "w_mg_combatmgmk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_09", model =  "w_mg_combatmgmk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_10", model =  "w_mg_combatmgmk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_IND_01", model =  "w_mg_combatmgmk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO", model =  "w_at_smgmk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_02", model =  "w_at_smgmk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_03", model =  "w_at_smgmk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_04", model =  "w_at_smgmk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_05", model =  "w_at_smgmk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_06", model =  "w_at_smgmk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_07", model =  "w_at_smgmk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_08", model =  "w_at_smgmk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_09", model =  "w_at_smgmk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_10", model =  "w_at_smgmk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_IND_01", model =  "w_at_smgmk2_camo_ind1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO", model =  "w_pi_pistolmk2_camo1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_02", model =  "w_pi_pistolmk2_camo2" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_03", model =  "w_pi_pistolmk2_camo3" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_04", model =  "w_pi_pistolmk2_camo4" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_05", model =  "w_pi_pistolmk2_camo5" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_06", model =  "w_pi_pistolmk2_camo6" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_07", model =  "w_pi_pistolmk2_camo7" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_08", model =  "w_pi_pistolmk2_camo8" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_09", model =  "w_pi_pistolmk2_camo9" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_10", model =  "w_pi_pistolmk2_camo10" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE", model =  "W_PI_PistolMK2_Camo_Sl_Ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_IND_01", model =  "w_pi_pistolmk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO", model =  "w_at_heavysnipermk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", model =  "w_at_heavysnipermk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", model =  "w_at_heavysnipermk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", model =  "w_at_heavysnipermk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", model =  "w_at_heavysnipermk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", model =  "w_at_heavysnipermk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", model =  "w_at_heavysnipermk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", model =  "w_at_heavysnipermk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", model =  "w_at_heavysnipermk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", model =  "w_at_heavysnipermk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01", model =  "w_at_heavysnipermk2_camo_ind1" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_FLSH_02", model =  "w_at_pi_flsh_2" }, 
    { bone = "WAPGrip", name =  "COMPONENT_AT_AR_AFGRIP_02", model =  "w_at_afgrip_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_01", model =  "w_at_muzzle_1" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_02", model =  "w_at_muzzle_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_03", model =  "w_at_muzzle_3" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_04", model =  "w_at_muzzle_4" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_05", model =  "w_at_muzzle_5" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_06", model =  "w_at_muzzle_6" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_07", model =  "w_at_muzzle_7" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_08", model =  "w_at_muzzle_8" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_09", model =  "w_at_muzzle_9" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_COMP", model =  "w_at_pi_comp_1" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_RAIL", model =  "w_at_pi_rail_1" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_MK2", model =  "w_at_scope_macro" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_02_MK2", model =  "w_at_scope_macro_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", model =  "w_at_scope_macro_2_mk2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL_MK2", model =  "w_at_scope_small" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", model =  "w_at_scope_small_mk2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MEDIUM_MK2", model =  "w_at_scope_medium_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE_MK2", model =  "w_at_scope_large" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_NV", model =  "w_at_scope_nv" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_THERMAL", model =  "w_at_scope_nv" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SIGHTS", model =  "w_at_sights_1" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SIGHTS_SMG", model =  "w_at_sights_smg" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_SR_SUPP_03", model =  "w_at_sr_supp3" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_FLASHLIGHT_LIGHT", model =  "w_me_flashlight_flash" }, 
    { bone = "WAPClip", name =  "COMPONENT_FLAREGUN_CLIP_01", model =  "w_pi_flaregun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CERAMICPISTOL_CLIP_01", model =  "W_PI_Ceramic_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CERAMICPISTOL_CLIP_02", model =  "w_pi_sns_pistol_mag2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_CERAMICPISTOL_SUPP", model =  "W_PI_Ceramic_Supp" }, 
    { bone = "WAPClip", name =  "COMPONENT_NAVYREVOLVER_CLIP_01", model =  "w_pi_wep2_gun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATSHOTGUN_CLIP_01", model =  "w_sg_pumpshotgunh4_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_GADGETPISTOL_CLIP_01", model =  "w_pi_singleshoth4_shell" }, 
    { bone = "WAPClip", name =  "COMPONENT_MILITARYRIFLE_CLIP_01", model =  "w_ar_bullpuprifleh4_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MILITARYRIFLE_CLIP_02", model =  "w_ar_bullpuprifleh4_mag2" }, 
    { bone = "WAPScop", name =  "COMPONENT_MILITARYRIFLE_SIGHT_01", model =  "w_ar_bullpuprifleh4_sight" }, 
    { bone = "WAPClip", name =  "COMPONENT_MACHINEPISTOL_CLIP_01", model =  "w_sb_compactsmg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MACHINEPISTOL_CLIP_02", model =  "w_sb_compactsmg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMPACTRIFLE_CLIP_01", model =  "w_ar_assaultrifle_smg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMPACTRIFLE_CLIP_02", model =  "w_ar_assaultrifle_smg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_DBSHOTGUN_CLIP_01", model =  "w_sg_doublebarrel_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_CLIP_01", model =  "w_pi_sns_pistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_CLIP_02", model =  "w_pi_sns_pistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPDW_CLIP_01", model =  "W_SB_PDW_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPDW_CLIP_02", model =  "W_SB_PDW_Mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANPISTOL_CLIP_01", model =  "W_PI_SingleShot_Shell" }, 
    { bone = "WAPClip", name =  "COMPONENT_EMPLAUNCHER_CLIP_01", model =  "W_LR_CompactML_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYRIFLE_CLIP_01", model =  "W_AR_SpecialCarbine_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYRIFLE_CLIP_02", model =  "W_AR_SpecialCarbine_mag2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYRIFLE_CAMO1", model =  "W_AT_HRH_Camo1" }, 
    { bone = "WAPScop", name =  "COMPONENT_HEAVYRIFLE_SIGHT_01", model =  "W_AR_HeavyRifleH_Sight" }, 
    { bone = "WAPClip", name =  "COMPONENT_TACTICALRIFLE_CLIP_01", model =  "w_ar_carbinerifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_TACTICALRIFLE_CLIP_02", model =  "w_ar_carbinerifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_PRECISIONRIFLE_CLIP_01", model =  "w_sr_w_sr_precisionrifle_reh_mag1" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_AR_FLSH_REH", model =  "W_AT_AR_Flsh_REH" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_CLIP_01", model =  "w_pi_sns_pistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNSPISTOL_CLIP_02", model =  "w_pi_sns_pistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYPISTOL_CLIP_01", model =  "w_pi_heavypistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYPISTOL_CLIP_02", model =  "w_pi_heavypistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_CLIP_01", model =  "w_ar_specialcarbine_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_CLIP_02", model =  "w_ar_specialcarbine_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_CLIP_01", model =  "w_ar_bullpuprifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_CLIP_02", model =  "w_ar_bullpuprifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_VINTAGEPISTOL_CLIP_01", model =  "w_pi_vintage_pistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_VINTAGEPISTOL_CLIP_02", model =  "w_pi_vintage_pistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MUSKET_CLIP_01", model =  "P_CS_Joint_02" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", model =  "w_at_scope_large" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_CLIP_01", model =  "w_sr_marksmanrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_CLIP_02", model =  "w_sr_marksmanrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSHOTGUN_CLIP_01", model =  "w_sg_heavyshotgun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSHOTGUN_CLIP_02", model =  "w_sg_heavyshotgun_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYPISTOL_CLIP_01", model =  "w_pi_heavypistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYPISTOL_CLIP_02", model =  "w_pi_heavypistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_CLIP_01", model =  "w_ar_specialcarbine_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SPECIALCARBINE_CLIP_02", model =  "w_ar_specialcarbine_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_GUSENBERG_CLIP_01", model =  "w_sb_gusenberg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_GUSENBERG_CLIP_02", model =  "w_sb_gusenberg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_RAILGUN_CLIP_01", model =  "w_ar_railgun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_CLIP_01", model =  "w_ar_bullpuprifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_BULLPUPRIFLE_CLIP_02", model =  "w_ar_bullpuprifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", model =  "w_ar_assaultriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", model =  "  w_ar_assaultriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", model =  "w_ar_assaultriflemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", model =  "w_ar_assaultriflemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", model =  "w_ar_assaultriflemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", model =  "w_ar_assaultriflemk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_01", model =  "w_ar_carbineriflemk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_02", model =  "w_ar_carbineriflemk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", model =  "w_ar_carbineriflemk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", model =  "w_ar_carbineriflemk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", model =  "w_ar_carbineriflemk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", model =  "w_ar_carbineriflemk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_01", model =  "w_mg_combatmgmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_02", model =  "w_mg_combatmgmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", model =  "w_mg_combatmgmk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_FMJ", model =  "w_mg_combatmgmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", model =  "w_mg_combatmgmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_MK2_CLIP_TRACER", model =  "w_mg_combatmgmk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_01", model =  "w_sr_heavysnipermk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", model =  "w_sr_heavysnipermk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", model =  "w_sr_heavysnipermk2_mag_ap" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", model =  "w_sr_heavysnipermk2_mag_ap2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", model =  "w_sr_heavysnipermk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", model =  "w_sr_heavysnipermk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_01", model =  "w_pi_pistolmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_02", model =  "w_pi_pistolmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_FMJ", model =  "w_pi_pistolmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", model =  "w_pi_pistolmk2_mag_hp" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", model =  "w_pi_pistolmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_MK2_CLIP_TRACER", model =  "w_pi_pistolmk2_mag_tr" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_01", model =  "w_sb_smgmk2_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_02", model =  "w_sb_smgmk2_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_FMJ", model =  "w_sb_smgmk2_mag_fmj" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", model =  "w_sb_smgmk2_mag_hp" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_INCENDIARY", model =  "w_sb_smgmk2_mag_inc" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_MK2_CLIP_TRACER", model =  "w_sb_smgmk2_mag_tr" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_AR_BARREL_01", model =  "w_at_ar_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_AR_BARREL_02", model =  "w_at_ar_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_CR_BARREL_01", model =  "w_at_cr_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_CR_BARREL_02", model =  "w_at_cr_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MG_BARREL_01", model =  "w_at_mg_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_MG_BARREL_02", model =  "w_at_mg_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SB_BARREL_01", model =  "w_at_sb_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SB_BARREL_02", model =  "w_at_sb_barrel_2" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SR_BARREL_01", model =  "w_at_sr_barrel_1" }, 
    { bone = "WAPBarrel", name =  "COMPONENT_AT_SR_BARREL_02", model =  "w_at_sr_barrel_2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO", model =  "w_at_armk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", model =  "w_at_armk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", model =  "w_at_armk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", model =  "w_at_armk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", model =  "w_at_armk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", model =  "w_at_armk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07", model =  "w_at_armk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", model =  "w_at_armk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", model =  "w_at_armk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", model =  "w_at_armk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01", model =  "w_at_armk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO", model =  "w_ar_carbineriflemk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_02", model =  "w_ar_carbineriflemk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_03", model =  "w_ar_carbineriflemk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_04", model =  "w_ar_carbineriflemk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_05", model =  "w_ar_carbineriflemk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_06", model =  "w_ar_carbineriflemk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_07", model =  "w_ar_carbineriflemk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_08", model =  "  w_ar_carbineriflemk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_09", model =  "  w_ar_carbineriflemk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_10", model =  "  w_ar_carbineriflemk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01", model =  "w_ar_carbineriflemk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO", model =  "w_mg_combatmgmk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_02", model =  "w_mg_combatmgmk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_03", model =  "w_mg_combatmgmk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_04", model =  "w_mg_combatmgmk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_05", model =  "w_mg_combatmgmk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_06", model =  "w_mg_combatmgmk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_07", model =  "w_mg_combatmgmk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_08", model =  "w_mg_combatmgmk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_09", model =  "w_mg_combatmgmk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_10", model =  "w_mg_combatmgmk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_COMBATMG_MK2_CAMO_IND_01", model =  "w_mg_combatmgmk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO", model =  "w_at_smgmk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_02", model =  "w_at_smgmk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_03", model =  "w_at_smgmk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_04", model =  "w_at_smgmk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_05", model =  "w_at_smgmk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_06", model =  "w_at_smgmk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_07", model =  "w_at_smgmk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_08", model =  "w_at_smgmk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_09", model =  "w_at_smgmk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_10", model =  "w_at_smgmk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_SMG_MK2_CAMO_IND_01", model =  "w_at_smgmk2_camo_ind1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO", model =  "w_pi_pistolmk2_camo1" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_02", model =  "w_pi_pistolmk2_camo2" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_03", model =  "w_pi_pistolmk2_camo3" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_04", model =  "w_pi_pistolmk2_camo4" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_05", model =  "w_pi_pistolmk2_camo5" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_06", model =  "w_pi_pistolmk2_camo6" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_07", model =  "w_pi_pistolmk2_camo7" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_08", model =  "w_pi_pistolmk2_camo8" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_09", model =  "w_pi_pistolmk2_camo9" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE", model =  "W_PI_PistolMK2_Slide_Camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_10", model =  "w_pi_pistolmk2_camo10" }, 
    { bone = "WAPCamo2", name =  "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE", model =  "W_PI_PistolMK2_Camo_Sl_Ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_PISTOL_MK2_CAMO_IND_01", model =  "w_pi_pistolmk2_camo_ind1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO", model =  "w_at_heavysnipermk2_camo1" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", model =  "w_at_heavysnipermk2_camo2" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", model =  "w_at_heavysnipermk2_camo3" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", model =  "w_at_heavysnipermk2_camo4" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", model =  "w_at_heavysnipermk2_camo5" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", model =  "w_at_heavysnipermk2_camo6" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", model =  "w_at_heavysnipermk2_camo7" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", model =  "w_at_heavysnipermk2_camo8" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", model =  "w_at_heavysnipermk2_camo9" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", model =  "w_at_heavysnipermk2_camo10" }, 
    { bone = "WAPCamo", name =  "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01", model =  "w_at_heavysnipermk2_camo_ind1" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_FLSH_02", model =  "w_at_pi_flsh_2" }, 
    { bone = "WAPGrip", name =  "COMPONENT_AT_AR_AFGRIP_02", model =  "w_at_afgrip_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_01", model =  "w_at_muzzle_1" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_02", model =  "w_at_muzzle_2" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_03", model =  "w_at_muzzle_3" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_04", model =  "w_at_muzzle_4" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_05", model =  "w_at_muzzle_5" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_06", model =  "w_at_muzzle_6" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_07", model =  "w_at_muzzle_7" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_08", model =  "w_at_muzzle_8_xm17" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_MUZZLE_09", model =  "w_at_muzzle_9" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_COMP", model =  "w_at_pi_comp_1" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_RAIL", model =  "w_at_pi_rail_1" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_MK2", model =  "w_at_scope_macro" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_02_MK2", model =  "w_at_scope_macro_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", model =  "w_at_scope_macro_2_mk2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL_MK2", model =  "w_at_scope_small" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", model =  "w_at_scope_small_mk2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MEDIUM_MK2", model =  "w_at_scope_medium_2" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE_MK2", model =  "w_at_scope_large" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_NV", model =  "w_at_scope_nv" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_THERMAL", model =  "w_at_scope_nv" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SIGHTS", model =  "w_at_sights_1" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SIGHTS_SMG", model =  "w_at_sights_smg" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_SR_SUPP_03", model =  "w_at_sr_supp3" }, 
    { bone = "WAPClip", name =  "COMPONENT_MUSKET_CLIP_01", model =  "p_w_ar_musket_chrg" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", model =  "w_at_scope_large" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_CLIP_01", model =  "w_sr_marksmanrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MARKSMANRIFLE_CLIP_02", model =  "w_sr_marksmanrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSHOTGUN_CLIP_01", model =  "w_sg_heavyshotgun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSHOTGUN_CLIP_02", model =  "w_sg_heavyshotgun_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_REVOLVER_CLIP_01", model =  "w_pi_revolver_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_AUTOSHOTGUN_CLIP_01", model =  "w_sg_sweeper_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMPACTLAUNCHER_CLIP_01", model =  "w_lr_compactgl_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MINISMG_CLIP_01", model =  "w_sb_minismg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MINISMG_CLIP_02", model =  "w_sb_minismg_mag2" }, 
    { bone = "WAPCover", name =  "COMPONENT_AT_RAILCOVER_01", model =  "w_at_railcover_01" }, 
    { bone = "WAPGrip", name =  "COMPONENT_AT_AR_AFGRIP", model =  "w_at_ar_afgrip" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_PI_FLSH", model =  "w_at_pi_flsh" }, 
    { bone = "WAPFlsh", name =  "COMPONENT_AT_AR_FLSH", model =  "w_at_ar_flsh" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MACRO", model =  "w_at_scope_macro" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_SMALL", model =  "w_at_scope_small" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MEDIUM", model =  "w_at_scope_medium" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_LARGE", model =  "w_at_scope_large" }, 
    { bone = "WAPScop", name =  "COMPONENT_AT_SCOPE_MAX", model =  "w_at_scope_max" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_PI_SUPP", model =  "w_at_pi_supp" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_AR_SUPP", model =  "w_at_ar_supp" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_AR_SUPP_02", model =  "w_at_ar_supp_02" }, 
    { bone = "WAPSupp", name =  "COMPONENT_AT_SR_SUPP", model =  "w_at_sr_supp" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_CLIP_01", model =  "w_pi_pistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL_CLIP_02", model =  "w_pi_pistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPISTOL_CLIP_01", model =  "w_pi_combatpistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATPISTOL_CLIP_02", model =  "w_pi_combatpistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_APPISTOL_CLIP_01", model =  "w_pi_appistol_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_APPISTOL_CLIP_02", model =  "w_pi_appistol_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MICROSMG_CLIP_01", model =  "w_sb_microsmg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MICROSMG_CLIP_02", model =  "w_sb_microsmg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_CLIP_01", model =  "w_sb_smg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_SMG_CLIP_02", model =  "w_sb_smg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_CLIP_01", model =  "w_ar_assaultrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTRIFLE_CLIP_02", model =  "w_ar_assaultrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_CLIP_01", model =  "w_ar_carbinerifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_CARBINERIFLE_CLIP_02", model =  "w_ar_carbinerifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ADVANCEDRIFLE_CLIP_01", model =  "w_ar_advancedrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ADVANCEDRIFLE_CLIP_02", model =  "w_ar_advancedrifle_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_MG_CLIP_01", model =  "w_mg_mg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_MG_CLIP_02", model =  "w_mg_mg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_CLIP_01", model =  "w_mg_combatmg_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_COMBATMG_CLIP_02", model =  "w_mg_combatmg_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSHOTGUN_CLIP_01", model =  "w_sg_assaultshotgun_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSHOTGUN_CLIP_02", model =  "w_sg_assaultshotgun_mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_SNIPERRIFLE_CLIP_01", model =  "w_sr_sniperrifle_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_HEAVYSNIPER_CLIP_01", model =  "w_sr_heavysniper_mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL50_CLIP_01", model =  "W_PI_PISTOL50_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_PISTOL50_CLIP_02", model =  "W_PI_PISTOL50_Mag2" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSMG_CLIP_01", model =  "W_SB_ASSAULTSMG_Mag1" }, 
    { bone = "WAPClip", name =  "COMPONENT_ASSAULTSMG_CLIP_02", model =  "W_SB_ASSAULTSMG_Mag2" }
    }