Config.BlockAttack = {
    [-1951375401] = true,
    [-1834847097] = true
}

Config.Modifier.Weapons = {
        [`WEAPON_UNARMED`] = {model = `WEAPON_UNARMED`, modifier = 0.22},
        [`WEAPON_NIGHTSTICK`] = {model = `WEAPON_NIGHTSTICK`, modifier = 0.33},
        [`WEAPON_FLASHLIGHT`] = {model = `WEAPON_FLASHLIGHT`, modifier = 0.13},
        [`WEAPON_KNIFE`] = {model = `WEAPON_KNIFE`, modifier = 0.33},
        [`WEAPON_KNUCKLE`] = {model = `WEAPON_KNUCKLE`, modifier = 0.33},
        [`WEAPON_NIGHTSTICK`] = {model = `WEAPON_NIGHTSTICK`, modifier = 0.33},
        [`WEAPON_HAMMER`] = {model = `WEAPON_HAMMER`, modifier = 0.23},
        [`WEAPON_BAT`] = {model = `WEAPON_BAT`, modifier = 0.33},
        [`WEAPON_BATTLEAXE`] = {model = `WEAPON_BATTLEAXE`, modifier = 0.13},
        [`WEAPON_GOLFCLUB`] = {model = `WEAPON_GOLFCLUB`, modifier = 0.33},
        [`WEAPON_CROWBAR`] = {model = `WEAPON_CROWBAR`, modifier = 0.33},
        [`WEAPON_BOTTLE`] = {model = `WEAPON_BOTTLE`, modifier = 0.33},
        [`WEAPON_DAGGER`] = {model = `WEAPON_DAGGER`, modifier = 0.33},
        [`WEAPON_WRENCH`] = {model = `WEAPON_WRENCH`, modifier = 0.33},
        [`WEAPON_STONE_HATCHET`] = {model = `WEAPON_STONE_HATCHET`, modifier = 0.33},
        [`WEAPON_KATANAS`] = {model = `WEAPON_KATANAS`, modifier = 0.33},
        [`WEAPON_HATCHET`] = {model = `WEAPON_HATCHET`, modifier = 0.33},
        [`WEAPON_MACHETE`] = {model = `WEAPON_MACHETE`, modifier = 0.33},
        [`WEAPON_SWITCHBLADE`] = {model = `WEAPON_SWITCHBLADE`, modifier = 0.33},
        [`WEAPON_PROXMINE`] = {model = `WEAPON_PROXMINE`, modifier = 0.33},
        [`WEAPON_BZGAS`] = {model = `WEAPON_BZGAS`, modifier = 0.13},
        [`WEAPON_SMOKEGRENADE`] = {model = `WEAPON_SMOKEGRENADE`, modifier = 0.13},
        [`WEAPON_MOLOTOV`] = {model = `WEAPON_MOLOTOV`, modifier = 0.13},
        [`WEAPON_POOLCUE`] = {model = `WEAPON_POOLCUE`, modifier = 0.43},
        [`WEAPON_PIPEWRENCH`] = {model = `WEAPON_PIPEWRENCH`, modifier = 0.33},
        --pistols
        [`WEAPON_PISTOL`] = {model = `WEAPON_PISTOL`, modifier = 0.63},
        [`WEAPON_COMBATPISTOL`] = {model = `WEAPON_COMBATPISTOL`, modifier = 0.58},
        [`WEAPON_SNSPISTOL`] = {model = `WEAPON_SNSPISTOL`, modifier = 0.53},
        [`WEAPON_CERAMICPISTOL`] = {model = `WEAPON_CERAMICPISTOL`, modifier = 0.53},
        [`WEAPON_PISTOL_MK2`] = {model = `WEAPON_PISTOL_MK2`, modifier = 0.58},
        [`WEAPON_PISTOL50`] = {model = `WEAPON_PISTOL50`, modifier = 0.63},
        [`WEAPON_APPISTOL`] = {model = `WEAPON_APPISTOL`, modifier = 0.43},
        [`WEAPON_VINTAGEPISTOL`] = {model = `WEAPON_VINTAGEPISTOL`, modifier = 0.43},
        [`WEAPON_DOUBLEACTION`] = {model = `WEAPON_DOUBLEACTION`, modifier = 0.43},
        [`WEAPON_REVOLVER`] = {model = `WEAPON_REVOLVER`, modifier = 0.33},
        [`WEAPON_NAVYREVOLVER`] = {model = `WEAPON_NAVYREVOLVER`, modifier = 0.33},
        [`WEAPON_MACHINEPISTOL`] = {model = `WEAPON_MACHINEPISTOL`, modifier = 0.48},
        [`WEAPON_SMG`] = {model = `WEAPON_SMG`, modifier = 0.43},
        [`WEAPON_SMG_MK2`] = {model = `WEAPON_SMG_MK2`, modifier = 0.43},
        [`WEAPON_ASSAULTSMG`] = {model = `WEAPON_ASSAULTSMG`, modifier = 0.5},
        [`WEAPON_MICROSMG`] = {model = `WEAPON_MICROSMG`, modifier = 0.43},
        [`WEAPON_MINISMG`] = {model = `WEAPON_MINISMG`, modifier = 0.38},
        [`WEAPON_COMBATPDW`] = {model = `WEAPON_COMBATPDW`, modifier = 0.38},
        [`WEAPON_COMPACTRIFLE`] = {model = `WEAPON_COMPACTRIFLE`, modifier = 0.38},
        [`WEAPON_PUMPSHOTGUN`] = {model = `WEAPON_PUMPSHOTGUN`, modifier = 0.43},
        [`WEAPON_SAWNOFFSHOTGUN`] = {model =`WEAPON_SAWNOFFSHOTGUN`, modifier = 0.23},
        [`WEAPON_DBSHOTGUN`] = {model = `WEAPON_DBSHOTGUN`, modifier = 0.43},
        [`WEAPON_GUSENBERG`] = {model = `WEAPON_GUSENBERG`, modifier = 0.33},
        [`WEAPON_MUSKET`] = {model = `WEAPON_MUSKET`, modifier = 0.43},
        [`WEAPON_MG`] = {model = `WEAPON_MG`, modifier = 0.43},
        [`WEAPON_ASSAULTRIFLE`] = {model = `WEAPON_ASSAULTRIFLE`, modifier = 0.48},
        [`WEAPON_ADVANCEDRIFLE`] = {model = `WEAPON_ADVANCEDRIFLE`, modifier = 0.48},
        [`WEAPON_BULLPUPRIFLE`] = {model = `WEAPON_BULLPUPRIFLE`, modifier = 0.48},
        [`WEAPON_ASSAULTRIFLE_MK2`] = {model = `WEAPON_ASSAULTRIFLE_MK2`, modifier = 0.38},
        [`WEAPON_GUSENBERG`] = {model = `WEAPON_GUSENBERG`, modifier = 0.43},
        [`WEAPON_CARBINERIFLE`] = {model = `WEAPON_CARBINERIFLE`, modifier = 0.48},
        [`WEAPON_M4A`] = {model = `WEAPON_M4A`, modifier = 1.2},
        [`WEAPON_M4B`] = {model = `WEAPON_M4B`, modifier = 1.4},
        [`WEAPON_G17A`] = {model = `WEAPON_G17A`, modifier = 0.47},
        [`WEAPON_G19`] = {model = `WEAPON_G19`, modifier = 0.68},
        [`WEAPON_G45`] = {model = `WEAPON_G45`, modifier = 1.2},
        [`WEAPON_AK74`] = {model = `WEAPON_AK74`, modifier = 1.0},
}