-- ESX MDT Shared Configuration
Config = {}

-- Jobs that can access MDT
Config.AllowedJobs = {
    'police',
    'ambulance',
    'government'
}

-- Police department configurations
Config.PoliceDepartments = {
    {
        id = 'lspd',
        name = 'Los Santos Police Department',
        shortName = 'LSPD'
    },
    {
        id = 'bcso',
        name = 'Blaine County Sheriff Office',
        shortName = 'BCSO'
    },
    {
        id = 'sasp',
        name = 'San Andreas State Police',
        shortName = 'SASP'
    }
}

-- Database tables
Config.Tables = {
    users = 'users',
    callsigns = 'mdt_callsigns',
    reports = 'mdt_reports',
    incidents = 'mdt_incidents',
    warrants = 'mdt_warrants',
    vehicles = 'owned_vehicles',
    properties = 'properties',
    evidence = 'mdt_evidence',
    people = 'mdt_people'
}

-- Permission levels by job grade
Config.Permissions = {
    police = {
        [0] = { -- Cadet
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            view_incidents = true,
            create_incidents = true,
        },
        [1] = { -- Officer  
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
        },
        [2] = { -- Sergeant (your current rank)
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
            view_warrants = true,
            create_warrants = true,
            edit_warrants = true,
            view_people = true,
            edit_people = true,
            view_vehicles = true,
            edit_vehicles = true,
            view_properties = true,
            view_firearms = true,
            view_evidence = true,
            create_evidence = true,
            view_roster = true,
            view_sops = true,
            view_comms = true,
            create_bolo = true,
            edit_bolo = true,
            PD_HIGH_COMMAND = true,
        },
        [3] = { -- Lieutenant
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
            manage_callsigns = true,
            view_warrants = true,
            create_warrants = true,
            edit_warrants = true,
            view_people = true,
            edit_people = true,
            view_vehicles = true,
            edit_vehicles = true,
            view_properties = true,
            view_firearms = true,
            view_evidence = true,
            create_evidence = true,
            view_roster = true,
            view_sops = true,
            view_comms = true,
            create_bolo = true,
            edit_bolo = true,
            PD_HIGH_COMMAND = true,
        },
        [4] = { -- Captain
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            delete_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
            delete_incidents = true,
            manage_callsigns = true,
            hire_fire = true,
            promote_demote = true,
            view_all_reports = true,
            system_admin = true,
            view_warrants = true,
            create_warrants = true,
            edit_warrants = true,
            delete_warrants = true,
            view_people = true,
            edit_people = true,
            delete_people = true,
            view_vehicles = true,
            edit_vehicles = true,
            view_properties = true,
            edit_properties = true,
            view_firearms = true,
            edit_firearms = true,
            view_evidence = true,
            create_evidence = true,
            edit_evidence = true,
            delete_evidence = true,
            view_roster = true,
            edit_roster = true,
            view_sops = true,
            edit_sops = true,
            view_comms = true,
            edit_comms = true,
            create_bolo = true,
            edit_bolo = true,
            delete_bolo = true,
            PD_HIGH_COMMAND = true,
            ["true"] = true, -- For system admin menu access
        },
        [5] = { -- Commander
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            delete_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
            delete_incidents = true,
            manage_callsigns = true,
            hire_fire = true,
            promote_demote = true,
            view_all_reports = true,
            view_warrants = true,
            create_warrants = true,
            edit_warrants = true,
            delete_warrants = true,
            view_people = true,
            edit_people = true,
            delete_people = true,
            view_vehicles = true,
            edit_vehicles = true,
            view_properties = true,
            edit_properties = true,
            view_firearms = true,
            edit_firearms = true,
            view_evidence = true,
            create_evidence = true,
            edit_evidence = true,
            delete_evidence = true,
            view_roster = true,
            edit_roster = true,
            view_sops = true,
            edit_sops = true,
            view_comms = true,
            edit_comms = true,
            create_bolo = true,
            edit_bolo = true,
            delete_bolo = true,
            PD_HIGH_COMMAND = true,
            ["true"] = true,
        },
        [10] = { -- Chief/Commissioner
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            delete_reports = true,
            view_incidents = true,
            create_incidents = true,
            edit_incidents = true,
            delete_incidents = true,
            manage_callsigns = true,
            hire_fire = true,
            promote_demote = true,
            view_all_reports = true,
            system_admin = true,
            view_warrants = true,
            create_warrants = true,
            edit_warrants = true,
            delete_warrants = true,
            view_people = true,
            edit_people = true,
            delete_people = true,
            view_vehicles = true,
            edit_vehicles = true,
            delete_vehicles = true,
            view_properties = true,
            edit_properties = true,
            delete_properties = true,
            view_firearms = true,
            edit_firearms = true,
            delete_firearms = true,
            view_evidence = true,
            create_evidence = true,
            edit_evidence = true,
            delete_evidence = true,
            view_roster = true,
            edit_roster = true,
            view_sops = true,
            edit_sops = true,
            view_comms = true,
            edit_comms = true,
            create_bolo = true,
            edit_bolo = true,
            delete_bolo = true,
            PD_HIGH_COMMAND = true,
            SAFD_HIGH_COMMAND = true,
            ["true"] = true,
        }
    },
    ambulance = {
        [0] = {
            mdt_access = true,
            view_reports = true,
            create_reports = true,
        },
        [5] = {
            mdt_access = true,
            view_reports = true,
            create_reports = true,
            edit_reports = true,
            manage_callsigns = true,
        }
    }
}